yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/',
         views.SignUp.as_view(), name='signup'
         ),
    path('logged_out/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logged_out'
         ),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
        name='password_change_form')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group',)
        labels = {'text': ('Текст'),
                  'group': ('Группа'),
                  }
        help_text = {
            'text': 'Поле для ввода текста поста',
            'group': 'Выберете соответствующую группу'
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from posts.models import User


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post

User = get_user_model()


def index(request: HttpRequest) -> HttpResponse:
    """Модуль отвечающий за главную страницу"""
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'post_list': post_list,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request: HttpRequest, slug) -> HttpResponse:
    """Модуль отвечающий за страницу сообщества"""
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'post_list': post_list,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request: HttpRequest, username) -> HttpResponse:
    """Модуль отвечающий за личную страницу"""
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    posts_count = posts.count()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'posts_count': posts_count,
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    """Модуль отвечающий за просмотр отдельного поста"""
    post = get_object_or_404(Post, pk=post_id)
    author_posts_count = Post.objects.filter(author_id=post.author_id).count()
    context = {
        'post': post,
        'post_id': post_id,
        'author_posts_count': author_posts_count,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request: HttpRequest) -> HttpResponse:
    """Модуль отвечающий за страницу создания текста постов."""
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request: HttpRequest, post_id: int) -> HttpResponse:
    """Модуль отвечающий за страницу редактирования текста постов."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post.pk)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.pk)
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block header %}Об авторе проекта{% endblock %}
{% block content %}
<h2>Привет, я автор</h2>
<p>
  Меня зовут Инна.<br>
  Мне 26 и я учусь на python-разработчика.<br>
  Вот ссылка на мой аккаунт в GitHub, где ты можешь увидеть все мои проекты: https://github.com/Jacky-Ink<br>
</p>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block header %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h2>Вот что я умею:</h2>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <h3 class="list-group-item">
        Python:
      </h3>
      <li>
        Декораторы
      </li>
      <h3 class="list-group-item">
        Django:
      </h3>
      <li>
        Paginator
      </li>
      <li>
        Контекст-процессоры
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {{ title }}
    </title>
    </head>
  <body>
    {% include 'includes/header.html'%}
    <main>
      <div class="container py-5">
        {% block content %}
          'пусто'
        {% endblock %}
      </div>
    </main>
      {% include 'includes/footer.html'%}
  </body>
</html>

yatube/templates/core/403csrf.html
{% extends "base.html" %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %} 

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'about:author' %}active{% endif %}"
              href="{% url 'about:author' %}">Об авторе
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'about:tech'%}active{% endif %}"
              href="{% url 'about:tech' %}">Технологии
            </a>
          </li>
          {%if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link
                {% if view_name == 'posts:post_create'%}active{% endif %}"
                href="{% url 'posts:post_create' %}">Новая запись
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light
                {% if view_name == 'users:password_change_form'%}active{% endif %}"
                href="{% url 'users:password_change_form' %}">Изменить пароль
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light
                {% if view_name == 'users:logged_out'%}active{% endif %}"
              href="{% url 'users:logged_out' %}">Выйти
            </a>
            </li>
            <li>
              Пользователь: {{ user.username }}
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link link-light" 
                {% if view_name == 'users:login' %}active{% endif %}
              href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light" 
                {% if view_name == 'users:signup' %}active{% endif %}
              href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
      {# Конец добавленого в спринте #}
    </div>
  </nav>
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% load user_filters %}

{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
           </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %} 
    {% block header %}
        Записи сообщества {{ group.title }}
    {% endblock %}
    {% block content %}  
        <h1>{{ group.title }}</h1> 
        <p> 
            {{ group.description|safe|linebreaksbr }} 
        </p> 
        {% for post in page_obj %} 
            <li> 
                Автор: {{ post.author.get_full_name }} 
                <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
                <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li> 
            <p>{{ post.text|safe|linebreaksbr }}</p> 
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        {% include 'includes/paginator.html' %}
    {% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
Последние обновления на сайте:
{% endblock %}

{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text|linebreaksbr }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
    <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
  {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
  {% endif %}
</article>
{% if not forloop.last %}
  <hr>
{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock%}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Пост: {{ post.text|truncatewords:30 }}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d M Y" }}
        </li>
        <li class="list-group-item">
          Группа:
          {% if post.group is not None %}  
          {{ post.group.title }}       
          <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
          {% endif %}
       </li>
        <li class="list-group-item">
          Автор: <span>{{ post.author.get_full_name }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span>{{ post.author.posts.count }}</span>
        </li>
       <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            Все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if post.author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          Редактировать пост
        </a>
      {% endif %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %} 
  <head>
    {% block tittle %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
  </head>
  <body>       
  {% block content %}
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ posts_count }} </h3>   
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">Все посты пользователя</a>
            </li>
            {% if post.group %}
            <li>
            Группа: {{ post.group }}
            </li>
            {% endif %}
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}  
            </li>
          </ul>
          <p>
            {{ post.text|linebreaksbr }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}"><u>Подробная информация </u></a>
        </article>       
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}"><u>Все записи группы</u></a>        
        {% endif %}
        {% endfor %}
        <hr>
        {% include 'includes/paginator.html' %} 
      </div>
    </main>
  {% endblock %}
  </body>

yatube/templates/users/logged_out.html
{% extends "base.html" %}
{% block title %}Вы вышли из системы{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Вы вышли из системы</div>
        <div class="card-body">
          <p>Вы вышли из своей учетной записи. Ждём вас снова!</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}

{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Войти на сайт</div>
        <div class="card-body">
          {% if form.errors %}
            <div class="alert alert-danger" role="alert">
              Имя пользователя и пароль не совпадают. Введите правильные данные.
            </div>
          {% endif %}

          {% if next %}
            <div class="alert alert-info" role="alert">
              Вы обратились к странице, доступ к которой возможен
              только для залогиненных пользователей.<br>
              Пожалуйста, авторизуйтесь.
            </div>
          {% else %}
            <div class="alert alert-info" role="alert">
              Пожалуйста, авторизуйтесь.
            </div>
          {% endif %}

          <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            <div class="form-group row">
              <label
                for="{{ form.username.id_for_label }}"
                class="col-md-4 col-form-label text-md-right">
                Имя пользователя
              </label>
              <div class="col-md-6">
                {{ form.username|addclass:"form-control" }}
              </div>
            </div>

            <div class="form-group row">
              <label
                for="{{ form.password.id_for_label }}"
                class="col-md-4 col-form-label text-md-right">
                Пароль
              </label>
              <div class="col-md-6">
                {{ form.password|addclass:"form-control" }}
              </div>
            </div>

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'password_reset' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Пароль изменён</div>
        <div class="card-body">
          <p>Пароль изменён успешно</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}

{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Изменить пароль</div>
        <div class="card-body">

          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ field.label }}: {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
          {% endif %}

          <form method="post">
            {% csrf_token %}

            {% for field in form %}
             <div class="form-group row">
                <label
                  class="col-md-5 text-md-right">
                  {{ field.label }}:
                </label>
                <div class="col-md-5 ">
                  {{ field }}
               </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>

        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля выполнен{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Пароль изменён</div>
        <div class="card-body">
          <p>Пароль изменён, всё получилось</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}

{% block content %}
  {% load user_filters %}
  {% if validlink %}

    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Введите новый пароль</div>
          <div class="card-body">

            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger" role="alert">
                    {{ field.label }}: {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
            {% endif %}

            <form method="post">
              {% csrf_token %}

              {% for field in form %}
                <div class="form-group row">
                  <label
                    class="col-md-5 text-md-right">
                    {{ field.label }}:
                  </label>
                  <div class="col-md-5 ">
                   {{ field }}
                  </div>
                </div>
              {% endfor %}

              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Назначить новый пароль
                </button>
              </div>
            </form>

          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->

  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  {% endif %}

{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Ссылка на восстановление пароля отправлена{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Пароль изменён</div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо 
              со ссылкой для восстановления пароля.</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  {# загружаем фильтр #}
  {% load user_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">

          {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}

          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required">*</span>
                  {% endif %}
                </label>
                <div class="col-md-6">
                  {# подключаем фильтр и указываем класс #}
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}